services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
      start_period: 10s

  webserver:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__DAG_DIR_LIST_INTERVAL=60
      - AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT=300
      - AIRFLOW__WEBSERVER__WORKERS=1
      - AIRFLOW__WEBSERVER__WORKER_CLASS=sync
      - AIRFLOW__CORE__PARALLELISM=2
      - AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG=2
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # 讓 DAG 可以 import 你的 src
      - PYTHONPATH=/opt/airflow:/opt/airflow/src
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./db:/opt/airflow/db
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
    ports:
      - "${WEB_PORT:-18080}:8080"
    command: >
      bash -lc "
        pip install --no-cache-dir -r /requirements.txt &&
        airflow db migrate &&
        airflow users create
          --username admin --password admin
          --firstname Johnny --lastname Yang
          --role Admin --email you@example.com || true &&
        exec airflow webserver
      "

  scheduler:
    image: apache/airflow:2.9.3
    depends_on:
      postgres:
        condition: service_healthy
      webserver:
        condition: service_started
    env_file: .env
    user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow:/opt/airflow/src
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./db:/opt/airflow/db
      - ./src:/opt/airflow/src
      - ./requirements.txt:/requirements.txt
    command: >
      bash -lc "
      pip install --no-cache-dir -r /requirements.txt &&
      exec airflow scheduler"

volumes:
  postgres-db-volume:
